
// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
//const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
   
//};

//export default sidebars;



export default {
  mySidebar: [
  
    {
      type: 'doc',
      id: 'README', 
      label: '关于', 
    },
    {
      type: 'doc',
      id: 'the-index', // document ID
      label: '索引', // sidebar label
    },
    {
      type: 'doc',
      id: 'timeline', // document ID
      label: '时间轴', // sidebar label
    },
    {
      type: 'category',
      label: '系列教程',            
      items: [
    {
      type: 'autogenerated',
      dirName: 'articles', // 自动抓取整个 articles
    },
    ],
    },
    {
     type: 'category',
     label: '研究记录',  
     link: {
      type: 'generated-index',
      slug: '/research-logs',
      "description": "研究过程和操作方法的备忘录",
    },      
     items: [{ type: 'autogenerated', dirName: 'articles/research-logs' }], // 只抓教程，干净清爽
    },
  ],
};





